In [ ]:
import numpy as np

In [ ]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
[i+2 for i in range(10)]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

## Creating numpy array

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
print(a)

[1 2 3 4 5 6]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
# np array from list
l=[1,2,3,4]
print(type(l))

ll=np.array(l)
print(type(ll))

<class 'list'>
<class 'numpy.ndarray'>


The arange function : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)

In [ ]:
h=np.arange(1,10)
print(h)

h=np.arange(10)
print(h)

h=np.arange(1,10,3)
print(h)

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 4 7]


The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [ ]:
k=np.linspace(1,2,3)
print(k)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [ ]:
np.empty((3,4), dtype=int)

array([[4.77852186e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Indexes

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
a[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
a[[0,4]]

array([1, 5])

In [ ]:
b=a[0:4]%2==0
a[a%2!=0]=0

print(b)
print(a)

[False  True False  True]
[0 2 0 4 0 6]


In [ ]:
s=np.array(['a','b','c','b','a'])
s[s!='a']='z'
print(s)

['a' 'z' 'z' 'z' 'a']


# Function

In [ ]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)

[ 1  2  3 10  5  6]


In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int8')

In [ ]:
a.size

6

In [ ]:
a.argmax()

3

In [ ]:
a.argmin()

0

In [ ]:
a.argsort()

array([0, 1, 2, 4, 5, 3])

In [ ]:
Z=np.zeros(10)

In [ ]:
print(Z)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
ZZ=np.zeros((2,3))

In [ ]:
print(ZZ)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ZZZ=np.zeros((2,3,4))

In [ ]:
print(ZZZ)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
O=np.ones(10)

In [ ]:
print(O)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
print(Z.dtype)

int32


In [ ]:
p=np.arange(9)

In [ ]:
print(p)

[0 1 2 3 4 5 6 7 8]


In [ ]:
k=p.reshape(3,3)
print(k)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(k.shape)

(3, 3)


In [ ]:
k.ndim

2

In [ ]:
# flatten
h=k.ravel()
print(h)

[0 1 2 3 4 5 6 7 8]


In [ ]:
print(h.shape)

(9,)


In [ ]:
b=np.arange(9).reshape(3,3)

In [ ]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.sum(b)

36

In [ ]:
# axis 0 = col
# axis 1 = row
np.sum(b,axis=0)

array([ 9, 12, 15])

In [ ]:
np.sum(b,axis=1)

array([ 3, 12, 21])

# Arithmatics

In [ ]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)

[ 1  2  3 10  5  6]


In [ ]:
print(a+2)

[ 3  4  5 12  7  8]


In [ ]:
print(a-2)

[-1  0  1  8  3  4]


In [ ]:
print(a+2,a-2,a*2,a/2,a**2)

[ 3  4  5 12  7  8] [-1  0  1  8  3  4] [ 2  4  6 20 10 12] [0.5 1.  1.5 5.  2.5 3. ] [  1   4   9 100  25  36]


In [ ]:
a=np.array([1,2,2,8,1,6,1],np.int8)
b=np.array([1,2,2,8,7,6,9],np.int32)
print(a+b)

[ 2  4  4 16  8 12 10]


In [ ]:
print(a==b)

[ True  True  True  True False  True False]


In [ ]:
print(a>=b)

[ True  True  True  True False  True False]


In [ ]:
print(a<=b)

[ True  True  True  True  True  True  True]


In [ ]:
print(a!=b)

[False False False False  True False  True]


In [ ]:
# transpose
b=np.array([1,2,2,8,7,6,9,10,11])

b=b.reshape(3,3)
b

array([[ 1,  2,  2],
       [ 8,  7,  6],
       [ 9, 10, 11]])

In [ ]:
b.T

array([[ 1,  8,  9],
       [ 2,  7, 10],
       [ 2,  6, 11]])

happy coding 😀